carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),

    path('checkout/', views.checkout, name='checkout'),
]

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),
]

superkart/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('securitypanel/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('orders/', include('orders.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
from django.db import models
from store.models import Product, Variation
from accounts.models import Account

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id
    
    class Meta:
        db_table = 'carts'
        ordering = ['-date_added']
        verbose_name = 'Cart'
        verbose_name_plural = 'Carts'
    
class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)
    
    def sub_total(self):
        return self.product.price * self.quantity
    
    def __unicode__(self):
        return self.product
    
    class Meta:
        db_table = 'cartitems'
        verbose_name = 'CartItem'
        verbose_name_plural = 'CartItems'

store/models.py
from django.db import models
from django.urls import reverse
from accounts.models import Account
from category.models import Category

class Product(models.Model):
    product_name    = models.CharField(max_length=200, unique=True)
    slug            = models.SlugField(max_length=200, unique=True)
    description     = models.TextField(max_length=500, blank=True)
    price           = models.IntegerField()
    images          = models.ImageField(upload_to='photos/products')
    stock           = models.IntegerField()
    is_available    = models.BooleanField(default=True)
    category        = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date    = models.DateTimeField(auto_now_add=True)
    modified_date   = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_name
    
    def average_rating(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=models.Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg
    
    def count_reviews(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=models.Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count
    
    class Meta:
        db_table = 'products'
        ordering = ['-created_date']              
        verbose_name = 'product'                 
        verbose_name_plural = 'products'
    
class VariationManager(models.Manager):
    def colors(self):
        return super().filter(variation_category='color', is_active=True)
    
    def sizes(self):
        return super().filter(variation_category='size', is_active=True)

variation_category_choice = (
    ('color', 'Color'),
    ('size', 'Size'),
)

class Variation(models.Model):
    product             = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category  = models.CharField(
        max_length=200, 
        choices=variation_category_choice,
        blank=True,
        null= True)
    variation_value     = models.CharField(
        max_length=200,
        blank=True,
        null=True)
    is_active           = models.BooleanField(default=True)
    created_date        = models.DateTimeField(auto_now_add=True)

    objects = VariationManager()

    def __str__(self):
        return f'{self.product.product_name} - {self.variation_category or "No Category"} : {self.variation_value or "No Value"}'
    
    class Meta:
        db_table = 'variations'
        ordering = ['-created_date']              
        verbose_name = 'variation'                 
        verbose_name_plural = 'variations'

class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject
    
    class Meta:
        db_table = 'reviewrating'
        ordering = ['created_at']              
        verbose_name = 'reviewrating'                 
        verbose_name_plural = 'reviewratings'

class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/products', max_length=255)

    def __str__(self):
        return self.product.product_name

    class Meta:
        db_table = 'productgallery'
        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery'

store/forms.py
from django import forms
from .models import ReviewRating

class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

carts/views.py
from django.shortcuts import render, redirect
from store.models import Product, Variation
from .models import Cart, CartItem
from django.http import HttpResponse
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import get_object_or_404

from django.contrib.auth.decorators import login_required

# for getting the cart id from session-id is present in the cookie session
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

# for adding the cart item
def add_cart(request, product_id):

    current_user = request.user
    # for getting the product
    product = Product.objects.get(id=product_id)

    # if current user is authenticated
    if current_user.is_authenticated:
        product_variation = []
        if request.method == 'POST':
            for key, value in request.POST.items():
                if key in ['color', 'size'] and value:
                    try:
                        variation = Variation.objects.filter(
                            product=product, 
                            variation_category__iexact=key, 
                            variation_value__iexact=value
                        ).first()
                        if variation:
                            product_variation.append(variation)
                    except Variation.DoesNotExist:
                        pass

        # for checking if the cart item already exists
        is_cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()
                
        # for checking existing variation list and current variation list          
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, user=current_user)

            # for getting the existing variation list and id list   
            existing_variation_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                existing_variation_list.append(list(existing_variation))
                id.append(item.id)

            # incrementing the quantity of the cart item
            if product_variation in existing_variation_list:
                index = existing_variation_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()

            # for creating the cart item
            else:
                item = CartItem.objects.create(
                    product=product,
                    quantity=1,
                    user=current_user
                )
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        # If the user is not authenticated
        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                user=current_user
                )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('cart')

    else:    
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                for key, value in request.POST.items():
                    if key in ['color', 'size'] and value:
                        try:
                            variation = Variation.objects.filter(
                                product=product, 
                                variation_category__iexact=key, 
                                variation_value__iexact=value
                            ).first()
                            if variation:
                                product_variation.append(variation)
                        except Variation.DoesNotExist:
                            pass
    
        # for getting the cart using the cart_id present in the session
        try:
            cart = Cart.objects.get(cart_id=_cart_id(request)) #get the cart using the cart_id present in the session
        except Cart.DoesNotExist:
            cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()

        # for checking if the cart item already exists
        is_cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()
                
        # for checking existing variation list and current variation list          
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, cart=cart)

            #existing_variation -> database
            #current variation -> product_variation
            #item in cart_item -> cart_item

            # for getting the existing variation list and id list   
            existing_variation_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                existing_variation_list.append(list(existing_variation))
                id.append(item.id)

            # incrementing the quantity of the cart item
            if product_variation in existing_variation_list:
                index = existing_variation_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()

            # for creating the cart item
            else:
                item = CartItem.objects.create(
                    product=product,
                    quantity=1,
                    cart=cart
                )
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        # for creating and saving cart item
        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                cart=cart
                )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('cart')

# for removing the cart item by reducing the quantity
def remove_cart(request, product_id, cart_item_id):
    
    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except Exception as e:
        pass
    return redirect('cart')

# for removing the cart all quantity item if quantity is more then one
def remove_cart_item(request, product_id, cart_item_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect('cart')

# for displaying the cart items
def cart(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0
        # for checking if the user is authenticated
        if request.user.is_authenticated:   
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (2 * total)/100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
    }
    return render(request, 'store/cart.html', context)

# for displaying the checkout page
@login_required(login_url='login')
def checkout(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0
        if request.user.is_authenticated:   
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (2 * total)/100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
    }
    return render(request, 'store/checkout.html', context)

templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="section-content padding-y bg">
    <div class="container">
        <!-- ============================ COMPONENT 1 ================================= -->
        <div class="card">
            <div class="row no-gutters">
                <aside class="col-md-6">
                    <article class="gallery-wrap"> 
                        <div class="img-big-wrap mainImage">
                        <center><img src="{{single_product.images.url}}" alt="Product Image"></center>
                        </div> <!-- img-big-wrap.// -->


                    </article> <!-- gallery-wrap .end// -->
                    <ul class="thumb">
                        <li>
                            <a href="{{single_product.images.url}}" target="mainImage"><img src="{{single_product.images.url}}" alt="Product Image"></a>
                            {% for i in product_gallery %}
                            <a href="{{i.image.url}}" target="mainImage"><img src="{{i.image.url}}" alt="Product Image"></a>
                            {% endfor %}
                        </li>
                        
                    </ul>
                </aside>
                <main class="col-md-6 border-left">

                    <form action="{% url 'add_cart' single_product.id %}" method="POST">
                        {% csrf_token %}
                        <article class="content-body">
                        
                        <h2 class="title">{{single_product.product_name}}</h2>
                        <div class="rating-star">
                            <span>
                                <i class="fa fa-star{% if single_product.average_rating < 0.5 %}-o{% elif single_product.average_rating >= 0.5 and single_product.average_rating < 1 %}-half-o{% endif %} aria-hidden="true"></i>
                                <i class="fa fa-star{% if single_product.average_rating < 1.5 %}-o{% elif single_product.average_rating >= 1.5 and single_product.average_rating < 2 %}-half-o{% endif %} aria-hidden="true"></i>
                                <i class="fa fa-star{% if single_product.average_rating < 2.5 %}-o{% elif single_product.average_rating >= 2.5 and single_product.average_rating < 3 %}-half-o{% endif %} aria-hidden="true"></i>
                                <i class="fa fa-star{% if single_product.average_rating < 3.5 %}-o{% elif single_product.average_rating >= 3.5 and single_product.average_rating < 4 %}-half-o{% endif %} aria-hidden="true"></i>
                                <i class="fa fa-star{% if single_product.average_rating < 4.5 %}-o{% elif single_product.average_rating >= 4.5 and single_product.average_rating < 5 %}-half-o{% endif %} aria-hidden="true"></i>
                            </span> 
                            <span>{{single_product.count_reviews}} reviews</span>  
                        </div>
                        
                        <div class="mb-3"> 
                            <var class="price h4">${{single_product.price}}</var> 
                        </div> 
                        
                        <p>{{single_product.description}}</p>
        

                        <hr>
                            <div class="row">
                                <div class="item-option-select">
                                    <h6>Choose Color</h6>
                                    <select name="color" class="form-control">
                                        <option value="" disabled selected>Select</option>
                                        {% for i in single_product.variation_set.colors %}
                                        <option value="{{i.variation_value | lower}}">{{i.variation_value | capfirst}}</option>
                                        {% endfor %}
                                    </select> 
                                </div>
                            </div> <!-- row.// -->
                            <div class="row">
                                <div class="item-option-select">
                                    <h6>Select Size</h6>
                                    <select name="size" class="form-control">
                                        <option value="" disabled selected>Select</option>
                                        {% for i in single_product.variation_set.sizes %}
                                        <option value="{{i.variation_value | lower}}">{{i.variation_value | capfirst}}</option>
                                        {% endfor %}
                                    </select> 
                                </div>
                            </div> <!-- row.// --> 
                        <hr>
                        {% if single_product.stock <= 0 %}
                        <h5 class="text-danger">Out of Stock</h5>
                        {% else %}
                            <button type="submit" class="btn  btn-primary"> <span class="text">Add to Cart</span> <i class="fas fa-shopping-cart"></i>  </button>
                        {% endif %}
                        </article> <!-- product-info-aside .// -->
                    </form>
                </main> <!-- col.// -->
            </div> <!-- row.// -->
        </div> <!-- card.// -->
        <!-- ============================ COMPONENT 1 END .// ================================= -->
        <br>
        <div class="row">
            <div class="col-md-9">
                
                <form action="{% url 'submit_review' single_product.id %}" method="post">
                    {% csrf_token %}
                    <h5>Leave a Review</h5>
                    <div class="row"> 
                        <div class="col-md-6">
                            <label>How would you rate the product?</label>
                            <br>
                            <div class="rate">
                                <input type="radio" name="rating" id="rating1" value="5"><label for="rating1" title="5"></label>
                                <input type="radio" name="rating" id="rating2" value="4.5"><label for="rating2" title="4.5" class="half"></label>
                                <input type="radio" name="rating" id="rating3" value="4"><label for="rating3" title="4"></label>
                                <input type="radio" name="rating" id="rating4" value="3.5"><label for="rating4" title="3.5" class="half"></label>
                                <input type="radio" name="rating" id="rating5" value="3"><label for="rating5" title="3"></label>
                                <input type="radio" name="rating" id="rating6" value="2.5"><label for="rating6" title="2.5" class="half"></label>
                                <input type="radio" name="rating" id="rating7" value="2"><label for="rating7" title="2"></label>
                                <input type="radio" name="rating" id="rating8" value="1.5"><label for="rating8" title="1.5" class="half"></label>
                                <input type="radio" name="rating" id="rating9" value="1"><label for="rating9" title="1"></label>
                                <input type="radio" name="rating" id="rating10" value="0.5"><label for="rating10" title="0.5" class="half"></label>
                            </div>
                            <br>
                            <label>Review Title:</label>
                            <input type="text" class="form-control" name="subject" placeholder="Write a review title">
                            <br>
                            <label>Review:</label>
                            <textarea class="form-control" name="review" placeholder="Write your review here" rows="4"></textarea>
                            <br>
                            {% if user.is_authenticated %}
                              {% if orderproduct %}     
                              <input type="submit" value="Submit Review" class="btn btn-primary">
                              {% else %}
                              <p>to review this product please buy it first.</p>
                              {% endif %}
                            {% else %}
                            <p>Please login to submit a review<span class="text-danger">*<a href="{% url 'login' %}"> Login Now</a></span></p>
                            {% endif %}   
                        </div>
                    </div>
                    {% include 'includes/alerts.html' %}
                </form> 

                <header class="section-heading">
                    <h3>Customer Reviews </h3>
                    <div class="rating-star">
                        <span>
                            <i class="fa fa-star{% if single_product.average_rating < 0.5 %}-o{% elif single_product.average_rating >= 0.5 and single_product.average_rating < 1 %}-half-o{% endif %} aria-hidden="true"></i>
                            <i class="fa fa-star{% if single_product.average_rating < 1.5 %}-o{% elif single_product.average_rating >= 1.5 and single_product.average_rating < 2 %}-half-o{% endif %} aria-hidden="true"></i>
                            <i class="fa fa-star{% if single_product.average_rating < 2.5 %}-o{% elif single_product.average_rating >= 2.5 and single_product.average_rating < 3 %}-half-o{% endif %} aria-hidden="true"></i>
                            <i class="fa fa-star{% if single_product.average_rating < 3.5 %}-o{% elif single_product.average_rating >= 3.5 and single_product.average_rating < 4 %}-half-o{% endif %} aria-hidden="true"></i>
                            <i class="fa fa-star{% if single_product.average_rating < 4.5 %}-o{% elif single_product.average_rating >= 4.5 and single_product.average_rating < 5 %}-half-o{% endif %} aria-hidden="true"></i>
                        </span>
                        <span>{{single_product.count_reviews}} reviews</span>    
                    </div>
                </header>
                  
                {% for review in reviews %} 
                <article class="box mb-3">
                    <div class="icontext w-100">

                        <div class="text">
                            <span class="date text-muted float-md-right">{{review.updated_at}}</span>  
                            <h6 class="mb-1">{{review.user.full_name}}</h6>
                            <div class="rating-star">
                                <span>
                                    <i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o{% endif %} aria-hidden="true"></i>
                                    <i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o{% endif %} aria-hidden="true"></i>
                                    <i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o{% endif %} aria-hidden="true"></i>
                                    <i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o{% endif %} aria-hidden="true"></i>
                                    <i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o{% endif %} aria-hidden="true"></i>
                                    
                                </span>
                            </div>
                        </div>
                    </div> <!-- icontext.// -->
                    <div class="mt-3">
                        <h6 class="mb-1">{{review.subject}} </h6>
                        <p class="mb-1">
                            {{review.review}}
                        </p>	
                    </div>
                </article>
                {% endfor %}
            </div> <!-- col.// -->
        </div> <!-- row.// -->
    </div> <!-- container .//  -->
</section>

{% endblock %}